services:
  - type: web
    name: ai-companion-server
    env: node
    plan: free
    rootDir: server
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: ai-companion-db
          property: connectionStringInternal
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://openrouter.ai/api
      - key: OPENAI_MODEL
        value: meta-llama/llama-3-8b-instruct:free
      - key: OPENAI_EMBED_MODEL
        value: nomic-ai/nomic-embed-text-v1.5

databases:
  - name: ai-companion-db
    plan: free
